### ISSUE TITLE
Unable to load libpython.so from apps (was: Building Dynamic version of library)

### ISSUE THREAD

**Issue by GRRedWings** [yan12125/python3-android#18] opened 2019-03-14 19:15 UTC
I'm probably doing something wrong, but in trying to use this library, I tried with no luck to link it static in my application, but I'm wondering if it's possible to build this as a shared object instead of a static library.

**Comment by yan12125** [comment] 2019-03-15 02:01
Could you give some more details?

**Comment by GRRedWings** [comment] 2019-03-15 09:41
I'm staying to build the file as an .so not a .a.  I have other so files in
my project, and was wondering if this is a configuration you have
available, or know of a quick way to achieve this.

---------------------------
Sent from my phone. Please forgive the short nature of the message, if
needed I will follow up with more details.

**Comment by yan12125** [comment] 2019-03-15 11:08
Do you mean files like libssl.a or libbz2.a? I built them as static libraries to avoid conflicts with vendor-supplied libraries in /system/lib or /system/lib64. If OpenSSL, BZip2 and so on are built as shared libraries (.so), LD_LIBRARY_PATH will be necessary to load them correctly, while setting this environment variable breaks vendor-supplied programs like /system/bin/toybox. I found this issue when I was using Android 6.0. Let me try if this is still an issue on Android 8.0.

If you want to try it out yourself, just remove `--disable-shared` from `pybuild/packages/*.py`.

**Comment by GRRedWings** [comment] 2019-03-15 11:10
Sorry, I was thinking the python file.  Libpython3.8m in particular

---------------------------
Sent from my phone. Please forgive the short nature of the message, if
needed I will follow up with more details.

**Comment by yan12125** [comment] 2019-03-15 18:07
Wow, good catch! I didn't notice libpython is built as a static library by default. Now fixed.

**Comment by GRRedWings** [comment] 2019-03-19 12:43
In trying to use the so file that is produced now, I get an error at runtime from the Android app saying that libpython3.8m.1.0 could not be found.  Is there something else that needs to be done, or could it be that I'm grabbing the wrong file?  I see that the 1.0 file is being produced, but renaming that does not work either.

**Comment by yan12125** [comment] 2019-03-19 12:56
Missing `$LD_LIBRARY_PATH`? This is what I use to run python3: https://github.com/yan12125/python3-android/blob/master/devscripts/env.sh

**Comment by GRRedWings** [comment] 2019-03-19 13:10
I'm not sure I follow. Everything builds, would I be able to get an outputed binary without this path?

**Comment by yan12125** [comment] 2019-03-20 16:34
I meant setting the environment variable LD_LIBRARY_PATH to the folder containing `libpython3.8m.1.0` before loading it. Seems the story is different if you use `System.loadLibrary()` from Java, though.

The simplest fix might be checking why the static library can't be linked. Reopening for further discussions - go back to static libraries or not?

**Comment by GRRedWings** [comment] 2019-03-20 17:57
For me I would prefer to use the static library and figure out why it's
unable to link at this time.  But I also understand your hesitation and
desire to revert back to what you had before.

But yes, we use System.loadLibrary().  Ex. from my java code

System.loadLibrary("python3.8m");

**Comment by yan12125** [comment] 2019-03-21 14:28
I'm fine with either static libraries or dynamic libraries, as long as it works. Mind to share error messages?

> System.loadLibrary("python3.8m");

Have you tried loading this library with absolute full path?

**Comment by GRRedWings** [comment] 2019-03-21 16:43
When using the old python3.5m from GRRedwings fork, I never needed to.  I can try.  

Here is the output of me trying to run the application with python3.8m

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.company.app, PID: 6058
    java.lang.UnsatisfiedLinkError: dlopen failed: library "libpython3.8m.so.1.0" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.company.app.activities.MyActivity.initLogger(WelcomeActivity.java:1170)
        at com.company.app.activities.MyActivity.onComplete(WelcomeActivity.java:926)
        at com.company.app.activities.BaseActivity$19.run(BaseServiceActivity.java:1923)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)

**Comment by GRRedWings** [comment] 2019-03-21 16:55
I'm wondering if this article can shed some light
https://stackoverflow.com/questions/33103867/unsatisfiedlinkerror-libcrypto-so-1-0-0-not-found

**Comment by yan12125** [comment] 2019-03-23 05:01
Does your fork build unversioned libpython shared library?

**Comment by GRRedWings** [comment] 2019-03-23 12:12
I believe so

---------------------------
Sent from my phone. Please forgive the short nature of the message, if
needed I will follow up with more details.

**Comment by yan12125** [comment] 2019-03-24 05:47
I created a new branch https://github.com/yan12125/python3-android/tree/unversioned-libpython that builds unversioned `libpython3.so`. Could you test it?

**Comment by GRRedWings** [comment] 2019-03-25 13:20
In my initial testing, the so file does not seem valid.  I get the
following error, even though I feel I have it included and linked properly.

What's different is that it's not a link error, as much as it's trying to find the full path from the dev box, not what is on the Android device.

2019-03-25 09:15:03.765 10812-10812/com.company.app E/AndroidRuntime: FATAL
EXCEPTION: main
    Process: com.company.app, PID: 10812
    java.lang.UnsatisfiedLinkError: dlopen failed: library
"D:/testing/android/company/mobile/src/main/jni/../jniLibs/arm64-v8a/
libpython3.8m.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at
com.company.app.activities.MainActivity.initLogger(MainActivity.java:1170)
        at
com.company.app.activities.MainActivity.onComplete(MainActivity.java:926)
        at
com.company.app.activities.BaseServiceActivity$19.run(BaseActivity.java:1923)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)


    --------- beginning of system

**Comment by yan12125** [comment] 2019-03-25 14:28
> D:/testing/android/company/mobile/src/main/jni/../jniLibs/arm64-v8a/libpython3.8m.so

Hmm it's kind of strange to see a Windows-style path. Anyway the error message seems to indicate that the file is not at the given path.

**Comment by GRRedWings** [comment] 2019-03-25 16:41
Going back to the original version of this library, it looks like Shizmob did more then just update the configure.ac.  Do more of these changes needs to be made to the current branch?

https://github.com/rave-engine/python3-android/commit/7ea569c74972c508a2d1ad617091e0aa0036447b

**Comment by yan12125** [comment] 2019-03-26 08:03
Hmm dunno why I removed that patch. Anyway from my understanding my patch is equivalent to Shizmob's - `configure` is renegerated based on `configure.ac` in `autoreconf` [1].

[1] https://github.com/yan12125/python3-android/blob/unversioned-libpython/pybuild/packages/python.py#L49

**Comment by edips** [comment] 2019-11-17 01:40
I built Python 3.9 without error. When I tried to use libpython3.9.so, I also got the error message `dlopen failed: library "libpython3.9.so.1.0" not found` on Qt. I used Python3.so statically from Shizmob 6 years ago. I had removed versioning from Python.so file using `rpl -R -e libpython3.2m.so.1.0 "libpython3.2.so\x00\x00\x00\x00\x00" .` now the script doesn't work :/

**Comment by yan12125** [comment] 2019-11-24 10:17
Sorry I can't help more here. I have no experience in loading `libpython.so` from applications other than the `python` binary, and the latter works for me for almost all the time. I'm afraid you'll need to debug the issue yourself.

**Comment by canewsin** [comment] 2020-01-23 01:06
i was now able to load python.so built without --enable-shared, but not sure about native modules, will soon post the update. libpython.so is not useful because it doesnot has python_main func which is in bin/python thus, packing bin/python in your app will work by including .so extension at the end

**Comment by yan12125** [comment] 2020-02-09 06:49
> library
"D:/testing/android/company/mobile/src/main/jni/../jniLibs/arm64-v8a/
libpython3.8m.so" not found

With the help of the sample app (https://github.com/GRRedWings/python3-android/tree/master/AndroidApp), I can now reproduce the issue. Looks like it is because libpythonthread.so uses the full path:
```
$ readelf -d ./app/build/intermediates/cmake/arm8ArmDebug/obj/arm64-v8a/libpythonthread.so | grep libpython3
 0x0000000000000001 (NEEDED)             Shared library: [/home/yen/tmp/python3-android/AndroidApp/app/src/main/jni/../jniLibs/arm64-v8a/libpython3.9.so]
```

**Comment by yan12125** [comment] 2020-02-09 07:09
@GRRedWings Could you try this patch? "It works!" for me :)

python32/python64 directories are for headers. Seems in the latest Python, 32/64 headers are not compatible and cannot be placed in the same directory.

```
diff --git a/AndroidApp/app/src/main/jni/CMakeLists.txt b/AndroidApp/app/src/main/jni/CMakeLists.txt
index 0761169..e92ed42 100644
--- a/AndroidApp/app/src/main/jni/CMakeLists.txt
+++ b/AndroidApp/app/src/main/jni/CMakeLists.txt
@@ -8,6 +8,12 @@ set(CMAKE_SYSTEM_VERSION 23)
 set(distribution_dir ${CMAKE_SOURCE_DIR}/../jniLibs)
 set(jni_src_dir ${CMAKE_SOURCE_DIR}/../jni)
 
+if("${CMAKE_SIZEOF_VOID_P}" STREQUAL "4")
+    include_directories(${jni_src_dir}/python32)
+else()
+    include_directories(${jni_src_dir}/python64)
+endif()
+
 # set all our include directories (header locations)
 include_directories(${jni_src_dir}/python
                     ${jni_src_dir}/py_helpers
@@ -15,8 +21,9 @@ include_directories(${jni_src_dir}/python
 )
 
 # define the 3rd party libraries to include in this project
-add_library(libpython35m SHARED IMPORTED)
-set_target_properties(libpython35m PROPERTIES IMPORTED_LOCATION ${distribution_dir}/${ANDROID_ABI}/libpython3.5m.so)
+#add_library(libpython39 SHARED IMPORTED)
+#set_target_properties(libpython39 PROPERTIES IMPORTED_LOCATION ${distribution_dir}/${ANDROID_ABI}/libpython3.9.so)
+link_directories(${distribution_dir}/${ANDROID_ABI})
 
 # set various C and CXX(++) flags
 set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -DNDEBUG")
@@ -35,6 +42,6 @@ SET_TARGET_PROPERTIES (pythonthread PROPERTIES LINKER_LANGUAGE CXX)
 
 # lastly, set to link against the 3rd party libs above
 target_link_libraries(pythonthread
-                      libpython35m
+                      python3.9
                       log
-                      atomic)
\ No newline at end of file
+                      atomic)
```

**Comment by GRRedWings** [comment] 2020-02-10 01:18
I will try to test this in the next few days

**Comment by GRRedWings** [comment] 2020-07-31 17:52
Yan, 

I have some free time again and I'm trying to get your fork to work with my application so we are not maintaining multiple code bases. I've posted another bug where I can't build in docker, but a co-worker can.  With the standard build we are getting the dynamic version of python (python3.9.a, the way I use it is this will not work as I need a static library.

I was able to edit configure.py to add --enabled-shared.  This built a versioned so though. Is it possible to build a non-versioned file?

**Comment by yan12125** [comment] 2020-08-01 06:14
I guess you were referring `build/usr/lib/libpython3.9.a`? It is already a static library.

**Comment by GRRedWings** [comment] 2020-08-01 12:13
I apologize, I was in a rush to update after a long day. I am able to output the static library libpython3.9.a that you reference, but I'd like to build the dynamic version. The problem is the dynamic version can't have versioning in it, as Android to my knowledge does not support that.  So when I tried to build the dynamic version I got libpython3.9.so.1.0, which I don't think works for Android. In your patch 3/24/2019 you had tried to patch configure.ac, I an wondering if this is something similar to what would need to be done?

**Comment by GRRedWings** [comment] 2020-08-02 17:32
I'm wondering if the only way for me to achieve what I would like is to patch configure.ac. Would this be done from configure.py?

**Comment by yan12125** [comment] 2020-08-03 05:49
I re-apply the unversioned-libpython patch on top of the current build scripts (2e1b1a7a303f771a149f0a8721ecc038036156bd). Could you give it a try?

**Comment by GRRedWings** [comment] 2020-08-04 21:14
I was able to build with this, but my test app is having issues attaching to that shared library.  I could be doing something wrong, but I'm wondering if we are building something different. In the old 3.5 version of mine, it would output a libpython3.5m.so, I'm not sure if the m was important.

E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.example.pythontest, PID: 8409
    java.lang.UnsatisfiedLinkError: dlopen failed: library "D:/SPE/_TestApps/Python3-Android/python3-android/AndroidApp/app/src/main/jni/../jniLibs/arm64-v8a/libpython3.9.so" not found: needed by /data/app/~~NVE7rdifl6mdHUsAZvb0Mw==/com.example.pythontest-u7ln5Tvgx-g56FSXieltow==/lib/arm64/libpythonthread.so in namespace classloader-namespace
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at com.example.pythontest.MainActivity.onCreate(MainActivity.java:29)

**Comment by GRRedWings** [comment] 2020-08-05 01:37
Another thing that I find odd and that I need to look into more is that in pyport.h I need to comment out the following check. When I try to build 64bit it fails if I do not

#if LONG_BIT != 8 * SIZEOF_LONG
/* 04-Oct-2000 LONG_BIT is apparently (mis)defined as 64 on some recent
 * 32-bit platforms using gcc.  We try to catch that here at compile-time
 * rather than waiting for integer multiplication to trigger bogus
 * overflows.
 */
#error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
#endif

**Comment by yan12125** [comment] 2020-08-05 01:53
> I was able to build with this, but my test app is having issues attaching to that shared library.

That looks similar to a previous issue (https://github.com/yan12125/python3-android/issues/18#issuecomment-476192901). Could you try [the patch](https://github.com/yan12125/python3-android/issues/18#issuecomment-583812880) above?

> Another thing that I find odd and that I need to look into more is that in pyport.h I need to comment out the following check. When I try to build 64bit it fails if I do not

Building arm64 with my scripts works
```
sudo docker run --rm -it --user $(id -u):$(id -g) -v $(pwd):/python3-android --env ARCH=arm64 --env ANDROID_API=21 python3-android-base
```

My patch above also handles headers for 32/64 differences.

> python32/python64 directories are for headers. Seems in the latest Python, 32/64 headers are not compatible and cannot be placed in the same directory.

I don't remember what was broken then, but it worths a try :)

**Comment by GRRedWings** [comment] 2020-08-05 02:19
I tried your patch above, but I'm not exactly sure what you are doing with your 32 bit and 64 bit directories.  I tried to apply this patch to my test app, and if I still need the changes to pyport.h, and I get undefined reference to PyGILState_Release if I comment out the following lines your patch shows

#add_library(libpython39 SHARED IMPORTED)
#set_target_properties(libpython39 PROPERTIES IMPORTED_LOCATION ${distribution_dir}/${ANDROID_ABI}/libpython3.9.so)

so do you have jni/python32 and jni/python64? I feel I'm missing something because that causes a number of errors for me.

**Comment by GRRedWings** [comment] 2020-08-05 02:33
Maybe it will help. I believe I have applied the above patch and builds from docker to a new app branch.
https://github.com/GRRedWings/python3-android/tree/Test-App-3.9

**Comment by yan12125** [comment] 2020-08-05 17:03
> so do you have jni/python32 and jni/python64?

Yep. `jni/python32` is copied from `build/usr/include` after building for arm and `jni/python64` is also from `build/usr/include` but after cleaning and building for arm64.

> Maybe it will help. I believe I have applied the above patch and builds from docker to a new app branch.

Well, there is a small difference - the library name is `python3.9` instead of `python39`.

**Comment by GRRedWings** [comment] 2020-08-05 18:15
With the python3.9 clue I was able to get it to run. But I still have to comment out the LONG_BIT, and I have to add back the add_library and set_target_property to your patch

**Comment by yan12125** [comment] 2020-08-07 16:19
I noticed I forgot to remove the include directory entry for the original headers in `python` after adding `python32` and `python64`.

https://github.com/GRRedWings/python3-android/blob/Test-App-3.9/AndroidApp/app/src/main/jni/CMakeLists.txt#L18

That looks like the cause of mismatched LONG_BIT values.

**Comment by GRRedWings** [comment] 2020-08-21 16:29
At this point we are able to build a unversioned library file from your branch with the patch. Is this something you plan to carry into master?

**Comment by yan12125** [comment] 2020-08-22 16:40
I added the patch to the master branch of this repo, while still keeping static libraries as the default - I believe static libraries can bring smaller binaries as well as slightly better performance. If you want to build dynamic libraries, re-run the `docker build` command and append configure arguments during building python3-android. For example,
```
docker run --rm -it --user $(id -u):$(id -g) -v $(pwd):/python3-android --env ARCH=arm --env ANDROID_API=21 python3-android-base --enable-shared
```

**Closed as completed by yan12125** 2020-08-22 16:40 UTC
